// programming  paradigm-> style or way of programming (way hai jisse aap programming kr skte ho)

let arr=[1,2,3,4,5,6,7,8]
 


// yha pta hai kaise kaam kr rha hai
// for(let i =0;i<arr.length;i++){
//     console.log(arr[i])
// }


// yeh pata nhi hai ki yeh internally kaise kaam krta hai ....but itn apta hai yeh kya kaam krta hai 
let result=arr.map((ele)=>{
    return ele})
    console.log(result)